# Generated by Django 4.0.6 on 2022-12-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('a1', models.IntegerField(default=0)),
                ('a2', models.IntegerField(default=0)),
                ('a3', models.IntegerField(default=0)),
                ('a4', models.IntegerField(default=0)),
                ('a5', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
